### ISSUE TITLE
data source

### ISSUE THREAD

**Issue by jeanfabrice94121** [nkaz001/algotrading-example#2]
Hi,

I was just trying to replicate your scripts crypto-scratch whose make use of data from tardis. I was able to download the sample data from this data provider but it appears to be not enough data to perform the entire analysis (in-out of sample periods).

I was wondering which data you are reading with the following command (e.g. xbtusd-normalization-market-making-backtest-hedge.ipynb ) :

df = pd.read_pickle('data2')

imbalace or trades? That you saved in a pickle object in the notebook : tardis-process.ipynb

Did you subscribe to tardis for additional data? what subscription plan would do the job (retrieving enough data to run your notebooks).

Any advice/recommendation is welcome. Thank you in advance. BTW nice job!
Jean-Fabrice

**Comment by nkaz001** [comment]
That's normalized orderbook imbalances. Please see `process_L2_normalization` in `tardis-process.ipynb`. 

In order to build the data, you need a full L2 order book(the most granular one) stream and a trade stream.

When I bought the data from tardis first there was a cheaper option, but now it seems that Solo Individual Exchange billed yearly is the cheapest option to access the full historical data they provided. I think you might need to talk with tardis for more detail.

Also, I got additional data for the early period from another source(an individual).

As the data cost gets increased, collecting the data by yourself would become a good option again.

I think data is one of the most difficult barriers for algotrading, but still getting crypto data is much cheaper and easier than others such as Nikkei, HSI, ES, and etc.

**Comment by jeanfabrice94121** [comment]
Thanks a lot for your answer. Regards, JF
