### ISSUE TITLE
Quote mid price calculation

### ISSUE THREAD

**Issue by theodoreromeos** [nkaz001/algotrading-example#3]
Can you explain how you calculate the new_bid and new_ask? What I don't get is how you compute the quote_mid_price. Does A stands for the quoted position? 

Thank you in advance for your response.

**Comment by nkaz001** [comment]
Have you read the references I refer to on the first page? This is inspired by these references. I strongly recommend you to read it

Page 5 in https://ieor.columbia.edu/files/seasdepts/industrial-engineering-operations-research/pdf-files/Borden_D_FESeminar_Sp10.pdf

BuyPrice = Mid-Market + A x Forecast –B x MCR – Current half-spread
SellPrice = Mid-Market + A x Forecast – B x MCR + Current half-spread

Here is my implementation.
quote_mid_price = row[close] + A * row[imbalance] / 100000000 + skew

row[close] = last traded price instead of mid-market((best_bid + best_ask) / 2)
A = a parameter you need to find.
row[imbalance] / 100000000 = forecast
skew = B * x / max_position * -1
So MCR is x / max_position and x is the holding position.
B = a parameter you need to find.

BuyPrice = quote_mid_price * (1 - half_spread)
SellPrice = quote_mid_price * (1 + half_spread)
half_spread = a parameter you need to find.
